services:
  app:
    build:
      context: ./app
    volumes:
        - ./app:/app
    ports:
      - "8000:8000"
    networks:
      - app-network 

  web:
    build:
      context: ./web
      target: dev
    depends_on:
      - app
    volumes:
      - ./web:/web
    ports:
      - "80:80"
      - "5173:5173"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
